matrix:
  include:
    - language: python
      python: 3.7
      before_install:
        - nvm install 10.18
        - nvm use 10.18      
      before_script:
        - sh tools/setup.sh
      script:
        - sh tools/test.sh
      after_success:
        - echo "todo: python coverage reporting to coveralls"
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sh tools/deploy.sh; fi
cache:
  directories:
    - ~/.npm
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
